### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by slrslr** [Olipro/ipset#3]
Hello,

i can blacklist set of IPs:
> iptables -A INPUT -m set --match-set blacklist src -j DROP

but how can i whitelist set of IPs and make iptables give higher priority to the whitelist than blacklist?

when i do:
> iptables -A INPUT -m set --match-set whitelist src -j ACCEPT

no matter if i order it after or before DROP rule, the DROP rule always override ACCEPT one. In other words, if blacklist contains an IP from whitelist, then such IP always gets blocked, which is unwanted by me.

> iptables -A INPUT -m set --match-set blacklist src **!** -m set --match-set whitelist src -J DROP

(this rule is most probably wrong, but could it work this way somehow?)

What is the correct way to do whitelist ips and make them override blacklist? Thank You

**Comment by Olipro** [comment]
What you are stating is impossible. `ACCEPT` is a terminating action. If you have your whitelist rule in front of the blacklist rule and it matches, evaluation will stop with the `ACCEPT` verdict.

Also, this isn't the place for support on how to use iptables.
