### ISSUE TITLE
Set type not supported

### ISSUE THREAD

**Issue by twitu** [Olipro/ipset#5]
Device details:
>Kernel: 4.15.0-43-generic
>OS: Ubuntu 16.04

I have installed the from source according to the given instructions. On doing `make modules_install` I encouter the following warning

> make -C /lib/modules/`uname -r`/build M=$PWD/kernel/net \
> 		KDIR=$PWD/kernel modules_install
> make[1]: Entering directory '/usr/src/linux-headers-4.15.0-43-generic'
> Makefile:975: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
>   INSTALL /home/ishan/Code/ipset/kernel/net/netfilter/ipset/ip_set.ko
> At main.c:160:
> - SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
> - SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
> sign-file: certs/signing_key.pem: No such file or directory
>   INSTALL /home/ishan/Code/ipset/kernel/net/netfilter/ipset/ip_set_bitmap_ip.ko
> At main.c:160:
> - SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
> - SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
> sign-file: certs/signing_key.pem: No such file or directory
>   INSTALL /home/ishan/Code/ipset/kernel/net/netfilter/ipset/ip_set_bitmap_ipmac.ko
> ===============================================================
> deleted messages for sake of clarity
> ===============================================================
> At main.c:160:
> - SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
> - SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
> sign-file: certs/signing_key.pem: No such file or directory
>   INSTALL /home/ishan/Code/ipset/kernel/net/sched/em_ipset.ko
> At main.c:160:
> - SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
> - SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
> sign-file: certs/signing_key.pem: No such file or directory
>   DEPMOD  4.15.0-43-generic
> make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-43-generic'
> 
> !!! WARNING !!! WARNING !!! WARNING !!!
> 
> Your distribution seems to ignore the /lib/modules/<kernelrelease>/extra/
> subdirectory, where the ipset kernel modules are installed.
> 
> Add the 'extra' directory to the search definition of your depmod
> configuration (/etc/depmod.conf or /etc/depmod.d/) and re-run
> 
> 	depmod <kernelrelease>
> 
> otherwise the ipset kernel modules in the extra subdir will be ignored.
> 
> 
> !!! WARNING !!! WARNING !!! WARNING !!!
> 
> Your running system has got ipset related kernel modules loaded in.
> You MUST rmmod the ip_set* kernel modules in order to make possible
> for the system to load in the newly installed ones.

At this point there is no module `ipset` or `ip_set` installed I checked using `modprobe` and by typing `ipset` into the CLI. However this problem is solved when I reboot, and this is output for a blank command
>ipset
>ipset v7.1: No command specified.
>Try `ipset help' for more information.

**Trying to create a set gives the following error**
>sudo ipset create test hash:ip,port,ip,port
>ipset v7.1: Kernel error received: set type not supported

**Comment by twitu** [comment]
Your last commit was helpful as I am trying to extend the module to support `bitmap:port,port`. But for some reason the functions in the last commit are not working.

**Comment by Olipro** [comment]
So, firstly, your kernel is configured to require signed kernel modules and it's failing to sign the built ones, so they probably wouldn't load even if you manually pointed `insmod` at them.

Secondly, the error message is also telling you what's wrong: namely that your kernel ignores the directory they get installed to. It also suggests a fix.

Your issue is out-of-scope for this repository as the error has nothing to do with ipset.
